language: python

services:
  - redis-server

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

  - "pypy3"
  - "nightly"

install:
  - pip install -r requirements.txt

script: python -m pytest --cov=./

after_success:
  - codecov