language: python
dist: xenial  # required for Python >= 3.7

services:
  - redis-server

python:
  - "3.6"
  - "3.7"
  - "nightly"

install:
  - pip install pytest-cov codecov
  - pip install -r requirements.txt

script: python -m pytest --cov=./

after_success:
  - codecov